/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.subViews;

import controlador.ValidacionesHelper;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;

/**
 *
 * @author mazal
 */
public class ModeloView extends javax.swing.JPanel {

    private static final Color GREEN_BORDER_COLOR = new Color(0, 128, 0);
    private static final Color RED_BORDER_COLOR = Color.RED;

    private final Border greenBorder = BorderFactory.createLineBorder(GREEN_BORDER_COLOR, 2);
    private final Border redBorder = BorderFactory.createLineBorder(RED_BORDER_COLOR, 2);

    /**
     * Creates new form MarcaView
     */
    public ModeloView() {
        initComponents();

        this.modelTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void validarCamposParaInsercion() {
        String name = this.modelName.getText(), year = this.modelYear.getText();

        boolean sonValidos = ValidacionesHelper.validarSoloNumerosFormatoAnio(year) && ValidacionesHelper.validarStringLongitudSinNumeros(name);

        this.modelInsert.setEnabled(sonValidos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        modelName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelYear = new javax.swing.JTextField();
        brandsComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        modelList = new javax.swing.JButton();
        modelDelete = new javax.swing.JButton();
        modelSave = new javax.swing.JButton();
        modelInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelTable = new javax.swing.JTable();

        modelName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modelNameKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Año");

        modelYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modelYearKeyReleased(evt);
            }
        });

        brandsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandsComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Marca");

        modelList.setText("Listar");

        modelDelete.setText("Borrar");
        modelDelete.setEnabled(false);
        modelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelDeleteActionPerformed(evt);
            }
        });

        modelSave.setText("Guardar Cambios");
        modelSave.setEnabled(false);

        modelInsert.setText("Insertar");
        modelInsert.setEnabled(false);
        modelInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelInsertActionPerformed(evt);
            }
        });

        modelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Marca", "Año"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(modelTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(modelName)
                        .addComponent(jLabel4)
                        .addComponent(modelYear)
                        .addComponent(brandsComboBox, 0, 182, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(modelInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(brandsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(modelInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelList))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelDeleteActionPerformed

    private void modelInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelInsertActionPerformed

    private void brandsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandsComboBoxActionPerformed

    private void modelNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelNameKeyReleased
        String valor = this.modelName.getText();
                
        this.modelName.setBorder(ValidacionesHelper.validarStringLongitudSinNumeros(valor) ? greenBorder : redBorder);
        
        this.validarCamposParaInsercion();
    }//GEN-LAST:event_modelNameKeyReleased

    private void modelYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelYearKeyReleased
        String valor = this.modelYear.getText();
                
        this.modelYear.setBorder(ValidacionesHelper.validarSoloNumerosFormatoAnio(valor) ? greenBorder : redBorder);
        
        this.validarCamposParaInsercion();
    }//GEN-LAST:event_modelYearKeyReleased

    public void limpiarCampos() {
        this.modelName.setText("");
        this.modelYear.setText("");

        this.modelName.setBorder(null);
        this.modelYear.setBorder(null);

        this.modelInsert.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> brandsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton modelDelete;
    public javax.swing.JButton modelInsert;
    public javax.swing.JButton modelList;
    public javax.swing.JTextField modelName;
    public javax.swing.JButton modelSave;
    public javax.swing.JTable modelTable;
    public javax.swing.JTextField modelYear;
    // End of variables declaration//GEN-END:variables
}
